#!/usr/bin/csh -f

rm -Rf svn-export internote-$1.xpi
svn export branches/3.0/extension svn-export
cd svn-export
mv chrome.manifest.release chrome.manifest
(cd chrome; zip -9 --recurse-paths --move internote.jar *)
zip -9 --recurse-paths ../internote-$1.xpi *
